import {
  Shirt,
  Cable,
  Baby,
  ShoppingCart,
  Handbag,
  Gem,
  Laptop,
  Globe2,
  Footprints,
  Calculator,
  Tv,
  Home,
  Blocks,
  Pill,
  Sparkles,
  Camera,
  Bike,
  ShoppingBag,
  PawPrint,
  Headphones,
  PenTool,
  Gamepad2,
  Package,
  type LucideIcon,
} from "lucide-react"

const CATEGORY_ICONS: Record<string, LucideIcon> = {
  "mens-apparel": Shirt,
  "mobiles-gadgets": Calculator,
  "mobiles-accessories": Cable,
  "home-entertainment": Tv,
  "babies-kids": Baby,
  "home-living": Home,
  groceries: ShoppingCart,
  "toys-games-collectibles": Blocks,
  "womens-bags": Handbag,
  "women-accessories": Gem,
  "womens-apparel": Shirt,
  "health-personal-care": Pill,
  "makeup-fragrances": Sparkles,
  "home-appliances": Home,
  "laptops-computers": Laptop,
  cameras: Camera,
  "sports-travel": Globe2,
  "mens-bags-accessories": ShoppingBag,
  "mens-shoes": Footprints,
  motors: Bike,
  "womens-shoes": Footprints,
  "pet-care": PawPrint,
  audio: Headphones,
  "hobbies-stationery": PenTool,
  gaming: Gamepad2,
}

export function CategoryPicture({ slug, className }: { slug: string; className?: string }) {
  const Icon = CATEGORY_ICONS[slug] ?? Package
  return <Icon className={className} strokeWidth={1.75} aria-hidden="true" />
}
